# Generated by Django 5.1.2 on 2024-11-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_request2_image1_alter_request2_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request2',
            name='completed_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
