# Generated by Django 5.1.2 on 2024-11-27 14:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_alter_request2_file1_alter_request2_file2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request2',
            name='file1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='request2',
            name='file2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='request2',
            name='file3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
