# Generated by Django 5.1.2 on 2024-11-22 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_request2_image1_alter_request2_image2_and_more'),
        ('manufacturer', '0007_alter_offer_request'),
        ('thierry', '0005_alter_admin_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=200)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturer.manufacturer')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturer.offer')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.request2')),
            ],
            options={
                'verbose_name': 'ClientPayment',
                'verbose_name_plural': 'ClientPayments',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ManufacturerWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=200)),
                ('paid', models.BooleanField(default=False)),
                ('payment_requested', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturer.manufacturer')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturer.offer')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.request2')),
            ],
            options={
                'verbose_name': 'ManufacturerWithdrawal',
                'verbose_name_plural': 'ManufacturerWithdrawals',
                'ordering': ('-created',),
            },
        ),
    ]
