# Generated by Django 5.1.2 on 2024-11-27 10:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thierry', '0006_clientpayment_manufacturerwithdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
