# Generated by Django 5.1.2 on 2024-11-27 10:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0007_alter_offer_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
